version: "3.9"

services:
    php-fpm:
        build:
            context: .
            dockerfile: ./docker/development/php-fpm/build/Dockerfile
        depends_on:
            - postgres

    nginx:
        build:
            context: .
            dockerfile: ./docker/development/nginx/build/Dockerfile
        depends_on:
            - php-fpm

    postgres:
        image: postgres:13.7-alpine
        environment:
            POSTGRES_DB: ${POSTGRES_DB}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_USER: ${POSTGRES_USER}
        volumes:
            - database:/var/lib/postgresql/data

    node:
        build:
            context: .
            dockerfile: ./docker/development/node/build/Dockerfile
        tty: true

volumes:
    database: ~
